### ISSUE TITLE
Element Out of grid

### ISSUE THREAD

**Issue by Flurrywinde** [justahuman1/i3-grid#2]
I ran `manager.sh` but I got: `Error: Element Out of grid`. Also, rofi reported a parser error (syntax error, unexpected invalid property value) in `matrix.rasi` on line 50, column 6-8.

**Comment by justahuman1** [comment]
Hi, what command did you execute? 

Line 50 is the background color of the UI ( `bg: ${BG};`), did you happen to change the background color? Can you upload the `theming` section of your `manager.sh`?

**Comment by Flurrywinde** [comment]
I just ran `./manager.sh` in the `~/.config/i3grid` directory. I didn't do anything with the background color, so the whole file, not just the `theming` section, is just like I got from the d/l link in the readme.

**Comment by justahuman1** [comment]
What shell are you using? What version of Rofi? Older versions of Rofi might not allow passing environment variables.

**Comment by justahuman1** [comment]
Was this resolved? If so, how?

**Comment by Flurrywinde** [comment]
Fish Shell v.3.1.2. Rofi v.1.5.0. It's still happening after upgrading to i3grid 0.2.3b3. I also git pulled the latest copies of manager.sh and matrix.rasi. Same thing is happening.
 
EDIT: Oh yeah, and also, yesterday, I tried it in gnome-terminal running bash (v.4.4.20(1)-release). It was the same there too.

EDIT 2: This was bugging me, so I looked it up. You're right; I need Rofi v.1.5.2 or greater, so I just had an adventure trying to compile the latest Rofi version. I got it working! So now `manager.sh` works. Life is good.

**Comment by justahuman1** [comment]
Glad it was fixed. It is definitely more powerful with a dmenu. For future users, please read the following:

I installed fish to confirm my suspicion. It did work on fish shell (which makes sense, as `manager.sh` has a bash header) and your experience confirms this, with the issue persisting on the bash shell. 

The issue was indeed the rofi version. Observing the [changelog](https://github.com/davatorium/rofi/blob/next/Changelog), environment variables were introduced in v1.5.2 (such as `${BG}`). The purpose of the environment variables is to allow for easy custom configuration of the color theme, ex:

<img src="https://i.imgur.com/rvi5CMf.png"/>

There are two possible fixes, both of which are fine:

1. Update Rofi (Minimum supported version: 1.5.2, I will update the README)
2. Remove the environment variables and replace them with the hardcoded styles (as seen in manager.sh or your personal choice of colors).

I uploaded a version with all the environment variables replaced in the matrix.rasi file to [Pastebin](https://pastebin.com/raw/QAZ7pJSz). Feel free to update the rasi file with that version.

I plan to use the environment variables in the future for dynamically changing the UI, so consider an update, if possible.
