### ISSUE TITLE
Uses a different python in i3 shortcut

### ISSUE THREAD

**Issue by Flurrywinde** [justahuman1/i3-grid#5]
I added the two i3 keybindings in the readme to my i3 config file, and though they ran, nothing happened. I tracked the issue down to anaconda. In a terminal, `anaconda3/bin` is in my $PATH, but it's not in the shell i3 uses when exec'ing keybindings. Thus, that python (`/usr/bin/python` vs `~/anaconda3/bin/python`) didn't have the i3grid package installed. I fixed it by exporting a new $PATH in manager.sh, but maybe there's a better way?

**Comment by justahuman1** [comment]
This seems more of an environment issue than it is related to i3-grid. I am curious how exactly you fixed it; I guess I could use a variable in the manager.sh rather than calling `python ...` per each switch statement. Something like: 
```
PY_ENV=/usr/bin/python3
...
$PY_ENV $grid_src center
```

Then the user can replace that python path with their preferred python environment, rather than replacing every variable. I will change this in the next commit.

I tried finding best practices for using python in bash script but all I found was calling `python` as usual. Let me know if you have any recommendations.

However, in this situation, I think you made the best decision, as it is easy to change whenever you switch an env as well. Is it (negatively) affecting the usage once you made the `export $PATH` fix?

**Comment by Flurrywinde** [comment]
Near the top of manager.sh, I added: `export PATH="/home/kanon/anaconda3/bin:$PATH"`. A better way might be to have users optionally set their alternate python path in the config file. Also, maybe manager.sh should popup an error if python doesn't have the i3grid package installed. As it was, the hotkey just didn't do anything, and that might be hard to diagnose.

I couldn't find anything about other people having this same problem either, which surprises me, but I did find people needing to have ...`anaconda3/bin` manually added to their $PATH at least. I suspect I did something odd when I installed anaconda, or maybe it has to do with the $PATH being correct only in the fish shell, not bash.

Well, in any event, all has been working well now that I updated the $PATH.
